#!/usr/bin/env ruby
# frozen_string_literal: true

require "rainbow"

warn(Rainbow("Calling erblint is deprecated, please call the renamed binstub `erb_lint` instead.").yellow)
exec(File.join(__dir__, "erb_lint"), *ARGV)
